### ISSUE TITLE
Files not copied from /etc/summit to $WILDFLY_HOME/standalone/configuration

### ISSUE THREAD

**Issue by lanroth** [soulwing/docker-wildfly10#1]
From the README.md:
You can place files in `/etc/summit` in an image based on this image. These files will copied to `$WILDFLY_HOME/standalone/configuration` when the image is started up the first time.

I think the script to do this is missing. I created a simple script to do this:
`151-copy-summit:
cp -v /etc/summit/* /var/run/wildfly/configuration`
which does the trick.
Great project - thanks :-)

**Comment by ceharris** [comment]
Actually, I meant to remove that part of the documentation. It was a leftover from when I extracted the Wildfly parts of this from its predecessor which included both Wildfly and an app named Summit.  In the image we use for Summit (which uses this as a base), we do exactly what you described -- add a script to copy stuff our app-specific configuration stuff into standalone/configuration.

I thought that this seemed pretty application specific, but perhaps not if you too found it useful.
Maybe having a directory (not named `/etc/summit`) to replace stuff in standalone/configuration is useful enough to keep?

**Comment by ceharris** [comment]
I'm thinking maybe any configuration files you place in `/etc/wildfly` (instead of `/etc/summit`) could be copied to `standalone/configuration`. It would copy only files, not directories, so `config.d` would be ignored.

**Comment by lanroth** [comment]
Ah, I was wondering why the directory was named summit, thanks for the explanation.

I think it's a useful feature. I'm just copying in `mgmt-users.properties` at the moment.

**Comment by lanroth** [comment]
That sounds like a nice neat way of doing it to me.

**Comment by ceharris** [comment]
Done. The image on Docker Hub should update shortly.

**Comment by ceharris** [comment]
FYI... found and fixed a bug in this today. Was inadvertently doing a recursive copy from`/etc/wildfly` to the wildfly configuration directory; intended to do a non-recursive copy of files in the top-level `/etc/wildfly` only.
