### ISSUE TITLE
Allow different interface binding for admin interface

### ISSUE THREAD

**Issue by mikesir87** [soulwing/docker-wildfly10#2]
When doing local dev, I may be using Traefik, so need to specify the `WILDFLY_BIND_INTERFACE` so the container will listen on the interface Traefik is sending requests to.  However, there's not a good way to also allow the admin interface to be accessible through Traefik.  I'd like to still bind the admin interface to 127.0.0.1, which my docker-compose.yml is exposing.

Took a look at where it would make most sense to slice that in and didn't come to a single spot.  Almost need an env variable for `WILDFLY_BIND_INTERFACE` and `WILDFLY_ADMIN_BIND_INTERFACE`.  Thoughts?

**Comment by ceharris** [comment]
Just to be clear, you're talking about the management UI and associated web services, right?

**Comment by mikesir87** [comment]
Correct.

**Comment by ceharris** [comment]
You can now specify `WILDFLY_MGMT_BIND_INTERFACE` in the same ways as `WILDFLY_BIND_ADDRESS`.
